AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend API for Portfolio Contact Form
  #Empty comment to push workflow trigger

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 128
    Timeout: 10 # Ample time for Boto3 to send the email
    # --- CRITICAL FIX: Use the local path to force SAM to package and upload ---
    CodeUri: contact_form/

Resources:
  # The Lambda Function that sends the email
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      # Grants permissions to log and, critically, to send emails via SES
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action: ses:SendEmail # Only permission needed to send email
            # LATEST UPDATE: Restricting permission to ONLY send from the verified xavieraws.com domain
            # IMPORTANT: The Resource ARN below uses a specific account ID (897279496475).
            # This ID must be accurate for your account and region (us-east-1).
            Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/xavieraws.com" 

      Events:
        ContactFormAPI:
          Type: Api
          Properties:
            Path: /contact
            Method: POST
            RestApiId: !Ref PortfolioContactApi # Reference the API Gateway defined below

  # The API Gateway that provides the public endpoint
  PortfolioContactApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # Ensures the API Gateway can be called from your portfolio domain
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'https://xavieraws.com'" # CHANGE THIS to your live domain, if different
        AllowCredentials: "'false'"

Outputs:
  ContactFormApi:
    Description: "API Gateway endpoint URL for Prod stage for Contact Form function"
    Value: !Sub "https://${PortfolioContactApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"
  ContactFormFunction:
    Description: "Contact Form Lambda Function ARN"
    Value: !GetAtt ContactFormFunction.Arn