name: SAM Deploy (Creates/Updates the CloudFormation Stack)

on:
push:
branches:
- main
paths:
- 'template.yaml'
- 'contact_form/**'

jobs:
deploy:
runs-on: ubuntu-latest
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_REGION: us-east-1

steps:
  - uses: actions:checkout@v4

  # 1. Setup AWS CLI and SAM CLI
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install SAM CLI
    run: pip install aws-sam-cli

  # 2. SAM Build (to create the deployment package)
  - name: SAM Build
    run: sam build --use-container
    # Ensures SAM is run from the root directory where template.yaml is located

  # 3. SIMPLIFIED DEPLOYMENT: Use sam deploy, which handles packaging/uploading automatically.
  # This replaces the complex 'sam package' and 'aws cloudformation deploy' steps.
  - name: Deploy Serverless Backend
    run: |
      sam deploy \
        --template-file .aws-sam/build/template.yaml \
        --stack-name serverless-portfolio-api \
        --region us-east-1 \
        --capabilities CAPABILITY_IAM \
        --s3-bucket xavieraws.com \
        --parameter-overrides DomainName=xavieraws.com \
        --no-confirm-changeset
