name: SAM Deploy (Creates/Updates the CloudFormation Stack)

on:
push:
branches:
- main
paths:
- 'template.yaml'
- 'contact_form/**'

jobs:
deploy:
runs-on: ubuntu-latest
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_REGION: us-east-1

steps:
  - uses: actions/checkout@v4

  # 1. Setup AWS CLI and SAM CLI
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install SAM CLI
    run: pip install aws-sam-cli

  # 2. SAM Build (to create the deployment package)
  - name: SAM Build (Prepares artifacts for s3 upload)
    run: sam build --template template.yml
    # Ensures SAM is run from the root directory where template.yaml is located

  # 3. FINAL DEPLOYMENT ATTEMPT: Use sam deploy with explicit artifact bucket and build output path.
  # This is the most reliable method for CI/CD environments.
  - name: Deploy Serverless Backend (Final Attempt)
    run: |
      sam deploy \
        --template-file .aws-sam/build/template.yml \
        --stack-name serverless-portfolio-api \
        --region us-east-1 \
        --capabilities CAPABILITY_IAM \
        --s3-bucket xavieraws.com \
        --parameter-overrides DomainName=xavieraws.com \
        --no-confirm-changeset
