name: SAM Deploy (Creates/Updates the CloudFormation Stack)

on:
push:
branches:
- main
paths:
- 'template.yaml'
- 'contact_form/**'

jobs:
deploy:
runs-on: ubuntu-latest
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_REGION: us-east-1

steps:
  - uses: actions/checkout@v4

  # 1. Setup AWS CLI and SAM CLI
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install SAM CLI
    run: pip install aws-sam-cli

  # 2. SAM Build (to create the deployment package)
  - name: SAM Build
    run: sam build --use-container
    # Ensures SAM is run from the root directory where template.yaml is located

  # 3. CRITICAL NEW STEP: SAM Package (Uploads code artifacts to S3)
  # This step creates and uploads the zipped Lambda code to the S3 bucket, outputting to packaged.yml.
  - name: SAM Package and Upload
    run: |
      sam package \
        --template-file .aws-sam/build/template.yaml \
        --s3-bucket xavieraws.com \
        --output-template-file packaged.yml
    # No working directory needed here as it defaults to the repo root

  # 4. AWS CloudFormation Deploy (Uses the packaged template)
  # This step deploys the S3-aware 'packaged.yml' file.
  - name: Deploy Serverless Backend
    run: |
      aws cloudformation deploy \
        --template-file packaged.yml \
        --stack-name serverless-portfolio-api \
        --region us-east-1 \
        --capabilities CAPABILITY_IAM \
        --parameter-overrides DomainName=xavieraws.com
