- name: Deploy
  run: sam deploy --stack-name serverless-portfolio-api --region us-east-1 --no-confirm-changeset --capabilities CAPABILITY_IAM --fail-on-empty-changeset --s3-bucket xavierawws.com
on:
  push:
    branches:
      - main

env:
  STACK_NAME: serverless-portfolio-api
  AWS_REGION: us-east-1 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::897279496475:role/MyProject_prod_CICD-Role
          role-session-name: github-actions-deployment 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy (Creates/Updates the CloudFormation Stack)
        run: sam deploy
          --stack-name ${{ env.STACK_NAME }}
          --region ${{ env.AWS_REGION }}
          --no-confirm-changeset
          --capabilities CAPABILITY_IAM
          --fail-on-empty-changeset # Prevents unnecessary runs if no code changed
